#! /bin/sh

# Startup stuff, that im too lazy to put elsewhere
sxhkd &
picom -b
xset r rate 400 44
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape

bspc monitor VGA-1 -d あ い
bspc monitor LVDS-1 -d う え お ' か ' # pad with spaces
bspc config border_width        0
bspc config window_gap          15
bspc config border_radius       15



# Set the border colors.
bspc config normal_border_color "#00000000"
bspc config active_border_color "#00000000"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#00000000"

bspc config -m VGA-1 top_padding -5
bspc config bottom_padding -5
bspc config -m LVDS-1 top_padding 20
bspc config left_padding -5
bspc config right_padding -5

bspc config split_ratio          0.50
bspc config gapless_monocle      false
bspc config click_to_focus        true

bspc config pointer_modifier mod1
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action1 move

bspc rule -a "feh" state=floating
bspc rule -a "zathura" state=tiled
bspc rule -a "xwinwrap" state=floating
bspc rule -a "net-runelite-launcher-Launcher" state=floating
bspc rule -a "xfce4-panel" layer=above
bspc rule -a "gifview" state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zoom state=floating
